### ISSUE TITLE
50% performance hit without warning

### ISSUE THREAD

**Issue by AGenchev** [pappacena/pytorch-rocm-gtt#1]
I get 50% performance hit when I use this hack. I think it should be mentioned together with the benefits of being able to use GTT memory that one also gets a performance degradation. Also some clues why this is happening might be mentioned.
The test code trains ResNet34 on cats/dogs dataset.
APU: 5600G / GFX900

**Comment by pappacena** [comment]
@AGenchev quick question to narrow down the issue: was the performance hit noticed also if you run training a second time?

I'm asking because in the first execution we compile the C code that handles memory allocation (which might take a few seconds). After the initial compilation, the lib should be cached and the execution should be faster.

**Comment by AGenchev** [comment]
Yes, it is consistent. But there is a remedy - kernel 6.10 comes with patches which make this hack unnecessary. I thought to implement a complex memory manager, but the kernel guys solved it quickly.
Here is the relevant discussion:
https://github.com/pytorch/pytorch/issues/107605#issuecomment-2242827413

**Comment by pappacena** [comment]
Great to know they fixed it at pytorch & kernel level! :tada:
